import { Time } from '@angular/common';

export class Anuncio{
  constructor(
    public id: number,
    public user: number,
    public titulo: string,
    public nombre_contacto: string,
    public descripcion: string,
    public subcategoria: number,
    public municipio: number,
    public lng: number,
    public lat: number,
    public telefono: string,
    public whatsapp: string,
    public email: string,
    public tipo_cobro: string,
    public tipo_servicio: string,
    public estatus: number,
    public vigencia: number,
    public imagen: string,
    public lunes: boolean,
    public martes: boolean,
    public miercoles: boolean,
    public jueves: boolean,
    public viernes: boolean,
    public sabado: boolean,
    public domingo: boolean,
    public lunes_inicio: Time,
    public lunes_fin: Time,
    public martes_inicio: Time,
    public martes_fin: Time,
    public miercoles_inicio: Time,
    public miercoles_fin: Time,
    public jueves_inicio: Time,
    public jueves_fin: Time,
    public viernes_inicio: Time,
    public viernes_fin: Time,
    public sabado_inicio: Time,
    public sabado_fin: Time,
    public domingo_inicio: Time,
    public domingo_fin: Time
  ){}
}